import { google } from "@ai-sdk/google"
import { Output, streamObject, streamText } from "ai"
import z from 'zod'

const result = streamText({
  model: google('gemma-4-26b-a4b-it:free'),
  prompt: `Give the first paragraph of a story about an imaginary planet.`
})

console.log('streamText:');
for await (const chunk of result.textStream) {
  process.stdout.write(chunk);
}
console.log('\n');

// ? It streams in token by token
/*
streamText:
The planet of Zog is a small, rocky world located in a distant galaxy.
It is home to a variety of strange and wonderful creatures, including the Zoglings, small, furry beings with large eyes and long tails. The planet's surface is covered in towering mountains and deep valleys, and its atmosphere is thick with a purple haze. Despite its harsh conditions, the Zoglings have thrived on their planet, developing advanced technology and a rich culture.
*/

const objectSchema = z.object({
  facts: z.array(z.string()).describe("An array of key facts from the text."),
})

const responseOutput = Output.object({
  schema: objectSchema,
  name: "text_output"
})

const { output } = streamText({
  model: google('gemma-4-26b-a4b-it:free'),
  output: responseOutput,
  prompt: `
    Give me an array of key facts from the following text

    ${await result.text}

    Remove all flowerly language. Speak as if you are a scientist.
  `
})

console.log('streamObject:');
const { facts } = await output;

for (const chunk of facts) {
  console.log(chunk);
}
console.log('\n');

// ? It's gonna create the object piece by piece streaming in the facts as they are generated by the model, so we can start consuming the output before the entire response is finished, which is super useful for long responses.
/*
streamObject:
{} // we first start out with an empty object

{ facts: [The planet of Zog is a small, rocky world located in a distant galaxy.]}

{ facts: ["The planet of Zog is a small, rocky world located in a distant galaxy.", 
 "It is home to a variety of strange and wonderful creatures, including the Zoglings, small, furry beings with large eyes and long tails." 
]}

{ facts: ["The planet of Zog is a small, rocky world located in a distant galaxy.", 
 "It is home to a variety of strange and wonderful creatures, including the Zoglings, small, furry beings with large eyes and long tails.", 
 "The planet's surface is covered in towering mountains and deep valleys." 
]}

{ facts: ["The planet of Zog is a small, rocky world located in a distant galaxy.", 
 "It is home to a variety of strange and wonderful creatures, including the Zoglings, small, furry beings with large eyes and long tails.", 
 "The planet's surface is covered in towering mountains and deep valleys.",
 "Its atmosphere is thick with a purple haze.",
 "Despite its harsh conditions, the Zoglings have thrived on their planet, developing advanced technology and a rich culture."
]}
*/